development:
  adapter: postgresql
  encoding: unicode
  database: ruby_gems_bootcamp_development
  pool: 5
  username: ol
  password: barby

test:
  adapter: postgresql
  encoding: unicode
  database: ruby_gems_bootcamp_test
  pool: 5
  username: ol
  password: barby

production:
  adapter: postgresql
  encoding: unicode
  database: ruby_gems_bootcamp_production
  pool: 5
  username: ol
  password: barby
